let access_token1="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkRGF0YSI6ImRhYzc5YWRmZDU2NzlmMWUzNzJkNDc3YjgxMjJlNmYwIiwiaWF0IjoxNzE2NDE4OTA0fQ.lkBugXMkdqREdEMTXUkrqi4DTY1Ci-GwnipLxtaRPy8"

let access_token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkRGF0YSI6ImRhYzc5YWRmZDU2NzlmMWUzNzJkNDc3YjgxMjJlNmYwIiwiaWF0IjoxNzE2NDE4OTA0fQ.lkBugXMkdqREdEMTXUkrqi4DTY1Ci-GwnipLxtaRPy8"
console.log(access_token1===access_token);